/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define GATTDB_xgatt_tag01                     12
#define GATTDB_xgatt_tag02                     14
#define GATTDB_xgatt_tag03                     16
#define GATTDB_xgatt_tag04                     18
#define GATTDB_xgatt_tag05                     20
#define GATTDB_xgatt_tag06                     22
#define GATTDB_xgatt_tag07                     24
#define GATTDB_xgatt_tag08                     26
#define GATTDB_xgatt_tag09                     28
#define GATTDB_xgatt_tag0a                     30
#define GATTDB_xgatt_tag0b                     32
#define GATTDB_xgatt_beaconM                   34

#endif
